name: Sports Calendar Engine

on:
  workflow_dispatch:

  schedule:
    # Every day at 03:00 UTC
    - cron: "0 3 * * *"

concurrency:
  group: sports-calendar-engine
  cancel-in-progress: true

jobs:
  build:

    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Calendars
        run: |
          python main.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit Updated Calendars
        run: |
          git add docs

          if git diff --cached --quiet; then
            echo "No calendar changes."
          else
            git commit -m "Automatic calendar update"
            git push
          fi